jobs:
  deploy:
    needs: [notify-slack]  # 'notify-slack' 작업 후 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Set environment variables
        run: echo "S3_BUCKET_NAME=cicd-joo-terraform" >> $GITHUB_ENV

      - name: Zip project files
        run: |
          zip -r deploy.zip ./*
        shell: bash

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://$S3_BUCKET_NAME/deploy.zip

      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name YourApplicationName \
            --deployment-group-name YourDeploymentGroup \
            --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy.zip
