name: Deployment with Slack Approval 

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'run tests'

  deploy-dev:
    name: Deploy(Dev)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'dev deployment'
  
  request-slack-approval:
    name: Request Slack Approval
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: your-channel-id
          SLACK_COLOR: '#FF0000'
          SLACK_MESSAGE: 'Deployment approval needed for ${{ github.sha }}. Please review the deployment plan.'
          SLACK_TITLE: 'Deployment Approval Required'

  deploy-production:
    name: Deploy(Production)
    needs: request-slack-approval
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: echo 'production deployment'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Set environment variables
        run: echo "S3_BUCKET_NAME=cicd-joo-terraform" >> $GITHUB_ENV
      - run: chmod +x scripts/deploy.sh
      - run: |
          zip -r $GITHUB_SHA.zip ./*
        shell: bash
      - run: |
          aws s3 cp --region ap-southeast-1 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip
      - run: |
          aws deploy create-deployment \
            --application-name joo-deploy-cicd \
            --deployment-group-name final \
            --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
