name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: Node.js 설정
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 의존성 설치
      run: |
        cd terraform
        npm install

    - name: 테스트 실행
      run: |
        cd terraform
        npm test

    - name: 프로젝트 빌드
      run: |
        cd terraform
        npm run build

    - name: 프로젝트 압축
      run: |
        cd terraform
        zip -r my-project.zip .

    - name: S3에 업로드
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp terraform/my-project.zip s3://cicd-joo-terraform/my-project.zip

    - name: CodeDeploy로 배포
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws deploy create-deployment \
          --application-name joo-deploy-cicd \
          --deployment-group-name joo-deploy-group \
          --s3-location bucket=cicd-joo-terraform,key=my-project.zip,bundleType=zip
