name: Deploy to AWS with Slack Approval via Webhook

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Set environment variables
      run: echo "S3_BUCKET_NAME=cicd-joo-terraform" >> $GITHUB_ENV

    - name: Grant execute permissions for deploy script
      run: chmod +x scripts/deploy.sh

    - name: Zip project files
      run: |
        zip -r $GITHUB_SHA.zip ./*
      shell: bash

    - name: Upload to S3
      env:
        S3_BUCKET_NAME: cicd-joo-terraform
      run: |
        aws s3 cp --region ap-southeast-1 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

    - name: Request approval from Slack via Webhook
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: your-channel-id
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: 'Deployment approval needed for ${{ github.sha }}. Please review the deployment plan.'
        SLACK_TITLE: 'Deployment Approval Required'

    - name: Deploy to CodeDeploy
      env:
        S3_BUCKET_NAME: cicd-joo-terraform
        environment: production  # Environment 설정 추가
      run: |
        aws deploy create-deployment \
          --application-name joo-deploy-cicd \
          --deployment-group-name final \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
